version: '3'

services:
  app:
    build:
      dockerfile: ./docker/php/Dockerfile
      context: .
    image: kaznishi/laravel-app
    environment:
      APP_KEY: base64:98hrEDhxAQ+HA0bmSuutVnrQ2tdfoDqCclWXc4tAooY=
  nginx:
    build:
      dockerfile: ./docker/nginx/Dockerfile
      context: .
    image: kaznishi/laravel-nginx
    ports:
      - "80:80"
    depends_on:
      - app
    environment:
      BACKEND_HOST: app
      LOG_STDOUT: "true"
