# version: '3'

# services:
#   app:
#     build: ./docker/php
#     volumes:
#       - ./:/var/www/html
#   node:
#     build: ./docker/node
#     volumes: 
#       - ./:/home/node/volume
#   nginx:
#     image: nginx
#     ports:
#       - '80:80'
#     volumes:
#       - ./:/var/www/html
#       - ./docker/nginx/php.conf:/etc/nginx/conf.d/default.conf
#     depends_on:
#       - app
version: '3'

services:
  app:
    build:
      dockerfile: ./docker/php/Dockerfile.prod
      context: .
    image: kaznishi/laravel-app
    environment:
      APP_KEY: base64:98hrEDhxAQ+HA0bmSuutVnrQ2tdfoDqCclWXc4tAooY=
    volumes:
      - ./:/var/www/html
  nginx:
    build:
      dockerfile: ./docker/nginx/Dockerfile.prod
      context: .
    image: kaznishi/laravel-nginx
    ports:
      - "80:80"
    depends_on:
      - app
    environment:
      BACKEND_HOST: app
      LOG_STROUT: "true"
    volumes:
      - ./:/var/www/html
  node:
    build: ./docker/node
    volumes: 
      - ./:/home/node/volume
