version: '3'

services:
  app:
    build:
      dockerfile: ./docker/php/Dockerfile.prod
      context: .
    image: kaznishi/laravel-app
  nginx:
    build:
      dockerfile: ./docker/nginx/Dockerfile.prod
      context: .
    image: kaznishi/laravel-nginx
