FROM node:8 AS node-builder

COPY . /home/node/html
WORKDIR /home/node/html

RUN yarn install
RUN npm run production

#######################################

FROM nginx:1-alpine

COPY --from=node-builder /home/node/html/public /var/www/html/public
COPY docker/nginx/php.conf.template /etc/nginx/conf.d/default.conf.template